# Generated by Django 5.2.5 on 2025-08-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='User',
        ),
    ]
